site_name: WearMe
theme:
  icon:
    admonition:
      example: simple/libreofficemath
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - content.footnote.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: lime
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

markdown_extensions:
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
extra:
  annotate:
    json: [.s2]

plugins:
  - search
  - mkdocstrings
  - glightbox
  - mkdocs-jupyter
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

nav:
  - Home: index.md
  - Bibliography notes:
    - Structural annotation based on Transformer: structural_annotation_molecules.md
  - Workflow:
    - General picture: Workflow.md
    - Training: training.md
    - Pre-prediction: PrePredictionWorkflow.md
    - Integrated pipeline: pipeline_integrated.md
  - API: 
    - Input Management: input.md
    - Signal Math: signalmath.md
    - Pre-prediction: preprediction.md
    - Prediction: prediction.md
  - API endpoints:
    - Pipeline API endpoints guide: README_flask_api.md
  - Tutorials:
    - Github setup: tutorial_github_setup.ipynb
    - Pre-prediction tutorial: tutorial_pipeline_preprocessing.ipynb
    - Prediction tutorial: tutorial_ms2_smiles.ipynb
    - End to end workflow script: tutorial_full_pipeline_script.ipynb